openapi: 3.0.0
info:
  title: Contador Playbacks API
  description: API para la app contador-playbacks
  contact:
    email: transformaciondigital@hogueras.es
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/federaciodefogueres/contador-playbacks-api/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Settings
  description: Settings available to manage the app
- name: Sesiones
  description: Sessions
- name: Asociaciones
  description: Asociaciones
- name: TypeSesion
  description: Tipos de sesión
paths:
  /sesiones:
    get:
      tags:
      - Sesiones
      description: Devuelve todas las sesiones con su información.
      operationId: getAllSessions
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsResponse'
      x-swagger-router-controller: Sesiones
    post:
      tags:
      - Sesiones
      description: Crea una sesión
      operationId: createSesion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Sesiones
  /sesiones/{idSession}:
    get:
      tags:
      - Sesiones
      description: Devuelve la información de la sesión solicitada.
      operationId: getSession
      parameters:
      - name: idSession
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
      x-swagger-router-controller: Sesiones
  /asociaciones:
    get:
      tags:
      - Asociaciones
      description: Devuelve todas las asociaciones con su información.
      operationId: getAllAsociaciones
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsociacionesResponse'
      x-swagger-router-controller: Asociaciones
    post:
      tags:
      - Asociaciones
      description: Crea una asociación
      operationId: createAsociacion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Asociacion'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Asociaciones
  /typeSesion:
    get:
      tags:
      - TypeSesion
      description: Devuelve todas las sesiones con su información.
      operationId: getAllTypeSesion
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TypeSessionResponse'
      x-swagger-router-controller: TypeSesion
  /mail:
    post:
      tags:
      - Settings
      summary: send an email
      description: Sends an email from the system
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailItem'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "201":
          description: email sent
        "400":
          description: invalid data
      x-swagger-router-controller: Settings
components:
  schemas:
    Response200:
      required:
      - message
      - status
      type: object
      properties:
        code:
          type: string
          example: "200"
        message:
          type: string
          example: Example message
      example:
        code: "200"
        message: Example message
    AsociacionesResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Response200'
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Asociacion'
      example:
        status:
          code: "200"
          message: Example message
        participants:
        - id: 12345678A
          title: Asociación inventada 1
          email: asociacion@gmail.com
        - id: 12345678A
          title: Asociación inventada 1
          email: asociacion@gmail.com
    TypeSessionResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Response200'
        types:
          type: array
          items:
            $ref: '#/components/schemas/TypeSession'
      example:
        types:
        - type_normalized: Eliminatoria
          id: 1
        - type_normalized: Eliminatoria
          id: 1
        status:
          code: "200"
          message: Example message
    SessionsResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Response200'
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/Session'
      example:
        sessions:
        - session_title: Sesión del día X
          type_normalized: Eliminatoria
          id: 12345678A
          type: 0
          participants:
          - id: 12345678A
            title: Asociación inventada 1
            email: asociacion@gmail.com
          - id: 12345678A
            title: Asociación inventada 1
            email: asociacion@gmail.com
        - session_title: Sesión del día X
          type_normalized: Eliminatoria
          id: 12345678A
          type: 0
          participants:
          - id: 12345678A
            title: Asociación inventada 1
            email: asociacion@gmail.com
          - id: 12345678A
            title: Asociación inventada 1
            email: asociacion@gmail.com
        status:
          code: "200"
          message: Example message
    SessionResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Response200'
        session:
          $ref: '#/components/schemas/Session'
      example:
        session:
          session_title: Sesión del día X
          type_normalized: Eliminatoria
          id: 12345678A
          type: 0
          participants:
          - id: 12345678A
            title: Asociación inventada 1
            email: asociacion@gmail.com
          - id: 12345678A
            title: Asociación inventada 1
            email: asociacion@gmail.com
        status:
          code: "200"
          message: Example message
    TypeSession:
      type: object
      properties:
        id:
          type: number
          example: 1
        type_normalized:
          type: string
          example: Eliminatoria
      example:
        type_normalized: Eliminatoria
        id: 1
    Session:
      type: object
      properties:
        id:
          type: string
          example: 12345678A
        session_title:
          type: string
          example: Sesión del día X
        type:
          type: number
          example: 0
        type_normalized:
          type: string
          example: Eliminatoria
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Asociacion'
      example:
        session_title: Sesión del día X
        type_normalized: Eliminatoria
        id: 12345678A
        type: 0
        participants:
        - id: 12345678A
          title: Asociación inventada 1
          email: asociacion@gmail.com
        - id: 12345678A
          title: Asociación inventada 1
          email: asociacion@gmail.com
    Asociacion:
      type: object
      properties:
        id:
          type: string
          example: 12345678A
        email:
          type: string
          example: asociacion@gmail.com
        title:
          type: string
          example: Asociación inventada 1
      example:
        id: 12345678A
        title: Asociación inventada 1
        email: asociacion@gmail.com
    EmailItem:
      required:
      - content
      - dataSesion
      - destine
      - sign
      - subject
      type: object
      properties:
        subject:
          type: string
          example: Testing email
        content:
          type: string
          example: Content testing email
        destine:
          type: string
          example: testing@mail.com
        dataSesion:
          type: string
          example: Primera sesión - Doctor Bergez
        sign:
          type: string
          example: image.png
    inline_response_200:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Response200'
      example:
        status:
          code: "200"
          message: Example message
